---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: loadbalancer-services
spec:
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cube-network-ip-pool"
spec:
  blocks:
    - start: "10.10.1.80"
      stop: "10.10.1.99"
