---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: loadbalancer-services
spec:
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "kind-network-ip-pool"
spec:
  blocks:
  - start: "10.5.0.100"
    stop: "10.5.0.200"
