---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starboard
  namespace: kube-system
  labels:
    app: starboard
spec:
  selector:
    matchLabels:
      app: starboard
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: starboard
    spec:
      volumes:
        - name: starboard
          hostPath:
            path: /dev/disk/by-id/usb-Adafruit_Matrix_Portal_M4_EA980545485437532020204E162319FF-0:0-part1
            type: BlockDevice
      containers:
        - name: shell
          image: "public.ecr.aws/jg/starboard:sidero"
          imagePullPolicy: Always
          securityContext:
            # seccompProfile:
            #   type: Unconfined
            # runAsNonRoot: false
            # capabilities:
            #   drop:
            #     - ALL
            privileged: true
          volumeMounts:
            - name: starboard
              mountPath: /dev/disk/by-id/usb-Adafruit_Matrix_Portal_M4_EA980545485437532020204E162319FF-0:0-part1
      nodeName: give-you
