---
apiVersion: v1
kind: Service
metadata:
  name: deathstar-lb
  namespace: default  
  labels:
    app.kubernetes.io/name: deathstar-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    org: empire
    class: deathstar
---
apiVersion: v1
kind: Service
metadata:
  name: deathstar-np
  namespace: default  
  labels:
    app.kubernetes.io/name: deathstar-np
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    org: empire
    class: deathstar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deathstar
  namespace: default  
  labels:
    app.kubernetes.io/name: deathstar
spec:
  replicas: 1
  selector:
    matchLabels:
      org: empire
      class: deathstar
  template:
    metadata:
      labels:
        org: empire
        class: deathstar
        app.kubernetes.io/name: deathstar
    spec:
      containers:
      - name: starwars
        image: cilium/starwars:v2.2
      nodeSelector:
        firewall: cilium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiefighter
  namespace: default  
  labels:
    app.kubernetes.io/name: tiefighter
spec:
  replicas: 1
  selector:
    matchLabels:
      org: empire
      class: tiefighter
  template:
    metadata:
      labels:
        org: empire
        class: tiefighter
        app.kubernetes.io/name: tiefighter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: firewall
                operator: NotIn
                values:
                - cilium
      containers:
      - name: spaceship
        image: docker.io/cilium/json-mock
